# Generated by Django 4.2.2 on 2023-06-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
