# Generated by Django 4.2.2 on 2023-06-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
