# Generated by Django 4.2.2 on 2023-06-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_customuser_test_field_alter_customuser_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(null=True, upload_to='public')),
            ],
        ),
    ]
