# Generated by Django 4.2.2 on 2023-06-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_fichetechnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fichetechnique',
            field=models.FileField(null=True, upload_to='public'),
        ),
    ]
