# Generated by Django 4.2.2 on 2023-06-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_customuser_fichetechnique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FicheTechnique',
        ),
    ]
