# Generated by Django 3.2.19 on 2023-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_auto_20230628_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
