# Generated by Django 3.2.19 on 2023-06-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_auto_20230629_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='recurrence',
        ),
    ]
