# Generated by Django 4.2.2 on 2023-06-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_delete_fichetechnique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(null=True, upload_to='public')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fichetechnique',
        ),
    ]
