# Generated by Django 3.2.19 on 2023-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_remove_events_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='recurrence',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
