# Generated by Django 4.2.2 on 2023-06-28 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_alter_customgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            #preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
