# Generated by Django 3.2.19 on 2023-06-29 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0008_events_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
