# Generated by Django 4.2.2 on 2023-06-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_alter_fichetechnique_fiche_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnique',
            name='Fiche_Technique',
            field=models.FileField(null=True, upload_to='media/public'),
        ),
    ]
