# Generated by Django 4.2.2 on 2023-06-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0011_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
