# Generated by Django 4.2.2 on 2023-06-30 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0013_technicalsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.IntegerField(choices=[('1', 'One Hour'), ('2', 'Two Hour'), ('3', 'Three Hour'), ('4', 'Four Hour'), ('5', 'Five Hour')])),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('Reserver', 'Reserved'), ('En cours', 'Inprogress')], max_length=20)),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studios.salle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
