# Generated by Django 4.2.2 on 2023-07-04 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0014_salle_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('est_approuve', models.BooleanField(default=False)),
                ('groupe1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerts_groupe1', to='studios.customgroup')),
                ('groupe2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerts_groupe2', to='studios.customgroup')),
                ('groupe3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerts_groupe3', to='studios.customgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
