# Generated by Django 4.2.2 on 2023-07-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0015_concert'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='planning',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studios.event'),
        ),
    ]
