# Generated by Django 4.2.2 on 2023-07-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0015_concert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='est_approuve',
            new_name='validated',
        ),
    ]
