# Generated by Django 4.2.2 on 2023-07-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0015_auto_20230705_0930'),
        ('studios', '0016_concert_planning'),
    ]

    operations = [
    ]
