# Generated by Django 4.2.2 on 2023-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0017_merge_0015_auto_20230705_0930_0016_concert_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
