# Generated by Django 4.2.2 on 2023-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0023_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=320, verbose_name='Adresse e-mail'),
        ),
    ]
