# Generated by Django 4.2.2 on 2023-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0024_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Email'),
        ),
    ]
