# Generated by Django 4.2.2 on 2023-07-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0028_technicalsheet_pdf_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalsheet',
            name='pdf_logo',
            field=models.FileField(null=True, upload_to='media/public'),
        ),
    ]
