# Generated by Django 4.2.2 on 2023-07-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0028_remove_customuser_test_field_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='twitter',
        ),
    ]
