# Generated by Django 4.2.2 on 2023-07-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0028_reservation_is_active_alter_reservation_duration'),
        ('studios', '0030_alter_customgroup_email_alter_customuser_email'),
        ('studios', '0030_alter_technicalsheet_pdf_file_and_more'),
    ]

    operations = [
    ]
