# Generated by Django 4.2.2 on 2023-07-07 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0034_customgroup_logo_customgroup_technical_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='biography',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(blank=True, max_length=320, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='genre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Style musicale'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de membres'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom de groupe'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='validated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Vérifié'),
        ),
    ]
