# Generated by Django 4.2.2 on 2023-07-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0038_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
