# Generated by Django 4.2.2 on 2023-07-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0039_delete_dummymodel_delete_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicalSheet',
        ),
    ]
