# Generated by Django 4.2.3 on 2023-07-10 14:04

from django.db import migrations, models
import studios.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0040_delete_technicalsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumTel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MODEL_GROUP_PHONE', models.CharField(blank=True, max_length=10, validators=[studios.fields.validate_phone_number], verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[studios.fields.validate_phone_number], verbose_name='Numéro de téléphone'),
        ),
    ]
