# Generated by Django 4.2.2 on 2023-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0041_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_confirm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Confirmer le mot de passe'),
        ),
    ]
