# Generated by Django 4.2.2 on 2023-07-10 14:26

from django.db import migrations, models
import studios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0042_customuser_password_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(blank=True, max_length=320, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
    ]
