# Generated by Django 4.2.2 on 2023-07-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0041_event_date'),
        ('studios', '0043_alter_customgroup_email_alter_customgroup_facebook_and_more'),
    ]

    operations = [
    ]
