# Generated by Django 4.2.2 on 2023-07-11 14:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import studios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0043_alter_customgroup_email_alter_customgroup_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='biography',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(max_length=320, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='genre',
            field=models.CharField(choices=[('black metal', 'Black Metal'), ('death_metal', 'Death Metal'), ('djent', 'Djent'), ('doom_metal', 'Doom Metal'), ('electro', 'Electro'), ('folk_metal', 'Folk Metal'), ('hardcore_punk', 'Punk Hardcore'), ('heavy_metal', 'Heavy Metal'), ('jazz', 'Jazz'), ('metal', 'Metal'), ('metalcore', 'Metalcore'), ('metal_industriel', 'Metal Industriel'), ('metal progressif', 'Metal Progressif'), ('metal_symphonique', 'Metal Symphonique'), ('modern_metal', 'Moderne Metal'), ('nu_metal', 'Nu Metal'), ('pop', 'Pop'), ('pop_rock', 'Pop Rock'), ('power_metal', 'Power Metal'), ('punk', 'Punk'), ('rock', 'Rock'), ('rock_alternatif', 'Rock Alternatif'), ('rock_progressif', 'Rock Progressif'), ('trash_metal', 'Trash Metal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de membres'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Nom de groupe'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='validated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vérifié'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_confirm',
            field=models.CharField(max_length=255, null=True, verbose_name='Confirmer le mot de passe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
    ]
