# Generated by Django 4.2.2 on 2023-07-11 11:07

import django.core.validators
from django.db import migrations, models
import studios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0043_alter_customgroup_email_alter_customgroup_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='biography',
            field=models.TextField(max_length=5000, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(max_length=320, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='facebook',
            field=models.URLField(null=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='genre',
            field=models.CharField(max_length=150, null=True, verbose_name='Style musicale'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='instagram',
            field=models.URLField(null=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='logo',
            field=models.FileField(null=True, upload_to='media/public', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de membres'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Nom de groupe'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='technical_sheet',
            field=models.FileField(null=True, upload_to='media/public', verbose_name='Fiche technique'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='validated',
            field=models.BooleanField(default=False, null=True, verbose_name='Vérifié'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_confirm',
            field=models.CharField(max_length=255, null=True, verbose_name='Confirmer le mot de passe'),
        ),
    ]
