# Generated by Django 4.2.2 on 2023-07-12 11:06

import django.core.validators
from django.db import migrations, models
import studios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0044_event_date_alter_customgroup_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, max_length=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de membres'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(error_messages={'phone_invalid': "Le numéro de téléphone saisi n'est pas valide."}, max_length=10, null=True, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(error_messages={'password_length': 'Votre mot de passe ne contient pas 8 caractères.', 'password_number': 'Votre mot de passe ne contient pas de chiffre.', 'password_special': 'Votre mot de passe ne contient pas de caractère spécial.', 'password_upper': 'Votre mot de passe ne contient pas de majuscule.'}, help_text=['Votre mot de passe doit contenir au moins 8 caractères.', 'Votre mot de passe doit contenir au moins 1 chiffre.', 'Votre mot de passe doit contenir au moins 1 majuscule.', 'Votre mot de passe doit contenir au moins 1 caractère spécial.'], max_length=255, validators=[studios.validators.length_validator, studios.validators.number_validator, studios.validators.upper_validator, studios.validators.special_validator], verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(error_messages={'phone_invalid': "Le numéro de téléphone saisi n'est pas valide."}, max_length=10, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
    ]
