# Generated by Django 4.2.2 on 2023-07-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0044_reservation_session_id_alter_reservation_duration_and_more'),
        ('studios', '0046_alter_customgroup_members'),
    ]

    operations = [
    ]
