# Generated by Django 4.2.2 on 2023-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0046_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='biography',
            field=models.TextField(max_length=5000, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='media/public', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='media/public', verbose_name='Fiche technique'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='validated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vérifié'),
        ),
    ]
