# Generated by Django 4.2.2 on 2023-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0046_alter_customgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, null=True, verbose_name='Nombre de membres'),
        ),
    ]
