# Generated by Django 4.2.2 on 2023-07-11 13:45

import django.core.validators
from django.db import migrations, models
import studios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0047_alter_customgroup_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='biography',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(max_length=320, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='genre',
            field=models.CharField(max_length=150, null=True, verbose_name='Style musicale'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de membres'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Nom de groupe'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
    ]
