# Generated by Django 4.2.2 on 2023-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0047_merge_20230712_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, null=True, verbose_name='Nombre de membres'),
        ),
    ]
