# Generated by Django 4.2.2 on 2023-07-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0048_alter_customgroup_biography_alter_customgroup_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='genre',
        ),
    ]
