# Generated by Django 4.2.2 on 2023-07-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0047_alter_customgroup_members'),
        ('studios', '0048_alter_customgroup_members'),
    ]

    operations = [
    ]
