# Generated by Django 4.2.2 on 2023-07-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0049_remove_customgroup_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='technical_sheet',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='validated',
        ),
    ]
