# Generated by Django 4.2.2 on 2023-07-11 13:50

import django.core.validators
from django.db import migrations, models
import studios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0050_remove_customgroup_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='biography',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(max_length=320, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='URL Facebook'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='URL Instagram'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='media/public', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de membres'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[studios.validators.phone_validator], verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='media/public', verbose_name='Fiche technique'),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='validated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vérifié'),
        ),
    ]
