# Generated by Django 4.2.2 on 2023-07-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0052_remove_customgroup_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='phone',
        ),
    ]
