# Generated by Django 4.2.2 on 2023-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0053_remove_customgroup_email_remove_customgroup_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='validated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vérifié'),
        ),
    ]
