# Generated by Django 4.2.2 on 2023-07-11 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0054_customgroup_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
