# Generated by Django 4.2.2 on 2023-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0057_alter_customgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='genre',
            field=models.CharField(choices=[('black metal', 'Black Metal'), ('death_metal', 'Death Metal'), ('djent', 'Djent'), ('doom_metal', 'Doom Metal'), ('electro', 'Electro'), ('folk_metal', 'Folk Metal'), ('hardcore_punk', 'Punk Hardcore'), ('heavy_metal', 'Heavy Metal'), ('jazz', 'Jazz'), ('metal', 'Metal'), ('metalcore', 'Metalcore'), ('metal_industriel', 'Metal Industriel'), ('metal progressif', 'Metal Progressif'), ('metal_symphonique', 'Metal Symphonique'), ('modern_metal', 'Moderne Metal'), ('nu_metal', 'Nu Metal'), ('pop', 'Pop'), ('pop_rock', 'Pop Rock'), ('power_metal', 'Power Metal'), ('punk', 'Punk'), ('rock', 'Rock'), ('rock_alternatif', 'Rock Alternatif'), ('rock_progressif', 'Rock Progressif'), ('trash_metal', 'Trash Metal')], max_length=100, null=True),
        ),
    ]
