# Generated by Django 4.2.2 on 2023-06-28 09:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_customgroup_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='biography',
            field=models.TextField(max_length=5000, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.CharField(max_length=320, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='genre',
            field=models.CharField(max_length=255, verbose_name='Style musicale'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='members',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de membres'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom de groupe'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Numéro de téléphone'),
        ),
    ]
