# Generated by Django 4.2.2 on 2023-06-28 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_customgroup_user_alter_customgroup_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
