# Generated by Django 4.2.2 on 2023-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0027_customuser_phone_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(error_messages={'unique': 'Cette adresse email est déjà utilisée.'}, max_length=320, unique=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': "Ce nom d'utilisateur est déjà utilisé"}, max_length=150, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
