# Generated by Django 4.2.2 on 2023-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0029_remove_customgroup_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='email',
            field=models.EmailField(max_length=320, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Cette adresse email est déjà utilisée.'}, max_length=320, unique=True, verbose_name='Adresse e-mail'),
        ),
    ]
