# Generated by Django 4.2.2 on 2023-07-07 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0031_merge_20230707_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_confirm',
            field=models.CharField(default=2, max_length=255, verbose_name='Confirmer le mot de passe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
