# Generated by Django 4.2.2 on 2023-07-10 10:04

from django.db import migrations, models
import studios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0040_delete_technicalsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255, validators=[studios.validators.length_validator, studios.validators.number_validator, studios.validators.upper_validator, studios.validators.special_validator], verbose_name='Mot de passe'),
        ),
    ]
